apiVersion: v1
kind: Secret
metadata:
  name: rds-creds
type: Opaque
stringData:
  application.properties: |
    database=mysql
    spring.datasource.url=jdbc:mysql://afeefpetclinicmysqldb.c3d0ws4ro7ne.us-east-2.rds.amazonaws.com/petclinic
    spring.datasource.initialization-mode=always
    spring.datasource.username=petclinic
    spring.datasource.password=petclinic

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: afeefpetclinicdeployment
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: afeefpetcliniccontainer
        image: 415102591172.dkr.ecr.us-east-2.amazonaws.com/afeef-petclinic-private:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /mnt
            name: afeef-petclinic-secret

      volumes:
        - name: afeef-petclinic-secret
          secret:
            secretName: rds-creds

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080